name: dougcrissman
favicon: null
layout_spectrum: 0.535473
typography_spectrum: 0.396959
title: Making Meaningless
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D8C0'
    - '#852500'
    - '#989070'
    - '#C83800'
    - '#000000'
  brandStrength: 0.579391
  lightness: 1
  saturation: 0.99831
  rhythmicContrast: 0.25
purpose: []
