analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#0B090A'
    - '#28272D'
    - '#838383'
    - '#3F484F'
  brandStrength: 0.440878
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.511824
cta: {}
layout_spectrum: 0.660473
name: dougcrissman
opengraph: {}
purpose: []
typography_spectrum: 0.44733
