name: dougcrissman
favicon: null
layout_spectrum: 0.9481995119713247
typography_spectrum: 0.24847322376444936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9741526008583605
  lightness: 0.021911089541390538
  saturation: 0.05942064383998513
  rhythmicContrast: 0.30760585772804916
purpose: []
