analytics: {}
color:
  brandColors:
    - '#79afbf'
    - '#fcfdff'
    - '#b2dbea'
    - '#1b3841'
    - '#62757f'
  brandStrength: 0.440878
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.511824
cta: {}
layout_spectrum: 0.58218
name: dougcrissman
opengraph: {}
purpose: []
typography_spectrum: 0.44733
