name: dougcrissman
favicon: null
layout_spectrum: 0.58218
typography_spectrum: 0.44733
title: Making Meaningless
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79afbf'
    - '#fcfdff'
    - '#b2dbea'
    - '#1b3841'
    - '#62757f'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
