analytics: {}
color:
  brandColors:
    - '#D8D8C0'
    - '#852500'
    - '#989070'
    - '#C83800'
    - '#000000'
  brandStrength: 0.579391
  lightness: 0.737331
  rhythmicContrast: 0.878378
  saturation: 0.99831
cta: {}
layout_spectrum: 0.535473
name: dougcrissman
opengraph: {}
purpose: []
typography_spectrum: 0.396959
